name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing and linting the codebase
on: [ push ]
jobs:
  test:
    strategy:
      matrix:
        go: [ 1.22.x, 1.23.x ]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: false
      - name: Display Go version
        run: go version
      - name: Run tests
        run: go test -v ./...
